# This configuration handles a repository with a static root
# and a sub-project that needs a build step.

[build]
  # This command builds ONLY the sub-project.
  command = "cd microkeebs && npm install && npm run build"

  # This publishes the ROOT of the repository, deploying all static files.
  publish = "."

# --- CORRECTED REDIRECTS ---
# The order of these rules is important.

# Rule 1: Serve the assets correctly.
# This rule tells Netlify to look inside the 'dist' folder for any requested assets.
[[redirects]]
  from = "/microkeebs/assets/*"
  to = "/microkeebs/dist/assets/:splat"
  status = 200

# Rule 2: Serve the main app for all other routes.
# This is the fallback for your Single Page App (SPA). It ensures that
# direct visits to /microkeebs or /microkeebs/some/page work correctly.
[[redirects]]
  from = "/microkeebs/*"
  to = "/microkeebs/dist/index.html"
  status = 200