# This is the netlify.toml for the MAIN micr.dev site.

[build]
  # This command is for your main site. If it's just static files, it can be empty.
  command = ""
  # This publishes the root of the repository, deploying all your static files.
  publish = "."

# --- PROXY RULE ---
# This rule tells Netlify how to handle the /microkeebs path.

[[redirects]]
  from = "/microkeebs/*"
  to = "https://microkeebs.netlify.app/:splat"
  status = 200