# This configuration handles a repository with a static root
# and a sub-project that needs a build step.

[build]
  # This command builds ONLY the sub-project.
  command = "cd microkeebs && npm install && npm run build"

  # This publishes the ROOT of the repository, deploying all static files.
  publish = "."

# --- CORRECTED REDIRECTS ---
# This is the standard and most reliable way to handle a Single Page App (SPA)
# like React/Vite in a subfolder.

[[redirects]]
  # When a user requests any path starting with /microkeebs/...
  from = "/microkeebs/*"
  # ...serve them the main index.html file from the build output.
  # React Router will then handle the specific route on the client-side.
  to = "/microkeebs/dist/index.html"
  # Status 200 means it's a successful rewrite, not a 301 redirect.
  status = 200