# This is the netlify.toml for the MAIN micr.dev site.

[build]
  # This command is for your main site. If it's just static files, it can be empty.
  command = ""
  # This publishes the root of the repository, deploying all your static files.
  publish = "."

# --- PROXY RULE ---
# This rule tells Netlify how to handle the /microkeebs path.

[[redirects]]
  # When a user requests /microkeebs/... on your main site...
  from = "/microkeebs/*"
  # ...invisibly fetch the content from your separate microkeebs site.
  # IMPORTANT: Replace the URL with the one you copied from Step 1!
  to = "https://microkeebs-unique-name.netlify.app/:splat"
  # Status 200! is crucial. It means "this is a rewrite, not a redirect".
  status = 200