# =============================================================================
# FINAL & FORCEFUL CONFIGURATION for a Monorepo with a Vite SPA
# =============================================================================

[build]
  command = "cd microkeebs && npm install && npm run build"
  publish = "."

# --- REDIRECT & REWRITE RULES ---
# The order and `force` attribute are critical.

# Rule 1: Serve assets correctly. This MUST be first.
[[redirects]]
  from = "/microkeebs/assets/*"
  to = "/microkeebs/dist/assets/:splat"
  status = 200

# Rule 2: Explicitly handle the base path WITHOUT a trailing slash.
# The 'force = true' overrides Netlify's default file-serving logic.
[[redirects]]
  from = "/microkeebs"
  to = "/microkeebs/dist/index.html"
  status = 200
  force = true
