# =============================================================================
# FINAL CONFIGURATION for a Monorepo with a Vite SPA in a subfolder
# =============================================================================

[build]
  # This command builds the Vite app inside the 'microkeebs' directory.
  command = "cd microkeebs && npm install && npm run build"

  # This publishes the entire repository root, deploying all static files
  # AND the newly built 'microkeebs/dist' folder.
  publish = "."

# --- REDIRECT & REWRITE RULES ---
# The order and content of these rules are critical.

# Rule 1: Asset Rewriting
# This rule ensures that requests for your app's assets (JS, CSS, images)
# are correctly served from the build output directory.
[[redirects]]
  from = "/microkeebs/assets/*"
  to = "/microkeebs/dist/assets/:splat"
  status = 200

# Rule 2: SPA Fallback / Catch-all
# This is the most important rule. It ensures that any direct navigation
# or refresh on a sub-page of your app (e.g., /microkeebs/build/123)
# serves the main index.html file, allowing React Router to handle the route.
[[redirects]]
  from = "/microkeebs/*"
  to = "/microkeebs/dist/index.html"
  status = 200